name:                we-control-your-money
version:             0.1.0.0
github:              "githubuser/we-control-your-money"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/we-control-your-money#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa ^>= 1.3.1
- csv == 0.1.2

library:
  source-dirs: src

executables:
  we-control-your-money-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - we-control-your-money

tests:
  we-control-your-money-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - we-control-your-money
